### ISSUE TITLE
请教一下天翼云cookies如何获得，似乎网页版cookies不可用

### ISSUE THREAD

**Issue by lhllhx** [liuqitoday/checkin-helper#3]
如题

**Comment by liuqitoday** [comment]
天翼云签到是 @gxitm 开发的，或许 @gxitm 看到后会回复。

**Comment by gaows20** [comment]
抓手机APP登录时候那个cookie

**Comment by lhllhx** [comment]
@gxitm 
抓包填入后无法登录 在response_checkin 中相应如下
'\n\n InvalidArgument\n sessionsignature is not match\n'

我是在iOS上抓的包 请问是要修改请求头 还是一定要在安卓上抓包

如果可以的话，能否提供一下cookies样式，参考一下。

**Comment by lhllhx** [comment]
找到问题了，需要修改请求头 估计signnature会对时间进行加密导致
抓包修改请求头后可以完成

**Comment by gaows20** [comment]
好的
