### ISSUE TITLE
关于微信提醒和联想社区签到的问题

### ISSUE THREAD

**Issue by orangexw** [liuqitoday/checkin-helper#4]
@gxitm 
1、如果我只想签到联想社区应该如何配置？
2、如果只是填写了联想社区的账号和cookie，运行main就会报错吗？就算填入了sckey，wechat也不会提醒？
小白一个，请大神详细说明一下使用规则。
下图是执行时报错
![TIM截图20200521123544](https://user-images.githubusercontent.com/55645077/82523723-9d364780-9b5f-11ea-868a-1b0d02b0bfb6.png)

**Comment by gaows20** [comment]
脚本不再更新，建议配置qiandao框架。https://github.com/qiandao-today

**Comment by orangexw** [comment]
> 脚本不再更新，建议配置qiandao框架。https://github.com/qiandao-today

好可惜。 @liuqitoday 还会更新吗？

**Comment by liuqitoday** [comment]
> > 脚本不再更新，建议配置qiandao框架。https://github.com/qiandao-today
> 
> 好可惜。 @liuqitoday 还会更新吗？

也是建议用qiandao框架吧，可以试试 http://qiandao.today/
